//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QLTS.DEMO.Web04.DTQUOC.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QLTS.DEMO.Web04.DTQUOC.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản .
        /// </summary>
        public static string AssetCode {
            get {
                return ResourceManager.GetString("AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bị trùng.
        /// </summary>
        public static string AssetCodeDuplicate {
            get {
                return ResourceManager.GetString("AssetCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được lớn hơn ngày bắt đầu sử dụng.
        /// </summary>
        public static string ChechUsingDateAndPurchaseDate {
            get {
                return ResourceManager.GetString("ChechUsingDateAndPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản.
        /// </summary>
        public static string CheckFormatAssetCode {
            get {
                return ResourceManager.GetString("CheckFormatAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn phải bằng 1/ số năm sử dụng.
        /// </summary>
        public static string CheckLifeTimeAndPercenAtrophy {
            get {
                return ResourceManager.GetString("CheckLifeTimeAndPercenAtrophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string CheckPurchaseDate {
            get {
                return ResourceManager.GetString("CheckPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu sử dụng không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string CheckUsingDate {
            get {
                return ResourceManager.GetString("CheckUsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database delete fail.
        /// </summary>
        public static string DevMsg_DeleteError {
            get {
                return ResourceManager.GetString("DevMsg_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched record error.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get record error.
        /// </summary>
        public static string DevMsg_GetDetail {
            get {
                return ResourceManager.GetString("DevMsg_GetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get record error.
        /// </summary>
        public static string DevMsg_GetRecord {
            get {
                return ResourceManager.GetString("DevMsg_GetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database insert fail.
        /// </summary>
        public static string DevMsg_InsertError {
            get {
                return ResourceManager.GetString("DevMsg_InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update fail.
        /// </summary>
        public static string DevMsg_UpdateError {
            get {
                return ResourceManager.GetString("DevMsg_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi không thành công.
        /// </summary>
        public static string UserMsg_DeleteError {
            get {
                return ResourceManager.GetString("UserMsg_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi không tồn tại.
        /// </summary>
        public static string UserMsg_GetDetail {
            get {
                return ResourceManager.GetString("UserMsg_GetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi không tồn tại.
        /// </summary>
        public static string UserMsg_GetRecord {
            get {
                return ResourceManager.GetString("UserMsg_GetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi không thành công.
        /// </summary>
        public static string UserMsg_InsertError {
            get {
                return ResourceManager.GetString("UserMsg_InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi không thành công.
        /// </summary>
        public static string UserMsg_UpdateError {
            get {
                return ResourceManager.GetString("UserMsg_UpdateError", resourceCulture);
            }
        }
    }
}
